### ISSUE TITLE
Installation issue for macOS Monterey 12.0.1 (M1 macs)

### ISSUE THREAD

**Issue by Jigme77** [emitanaka/deggust#9]
## Seems the issue is with dependencies, igraph  installation, couldn't find a workaround

installing *source* package ‘deggust’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: object ‘get_edibble_design’ is not exported by 'namespace:edibble'
Execution halted
ERROR: lazy loading failed for package ‘deggust’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/deggust’
Warning messages:
1: In i.p(...) : installation of package ‘igraph’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/vp/9f936cf54cb8fgrb3mhd4p5h0000gn/T//Rtmp2KjQXD/file5d5919f17b94/deggust_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by dicook** [comment]
If you install graph, and openxlsx first, then both edibble and deggust will install on an M1.

**Comment by emitanaka** [comment]
This issue was in edibble emitanaka/edibble#41 and should be fixed in new version (`igraph` is no longer used in `edibble`)
